### ISSUE TITLE
Fix template package.json license URL

### ISSUE THREAD

**Issue by necolas** [danheberden/yeoman-generator-requirejs#2]
Currently points to: https://github.com/danheberden/gith/blob/master/LICENSE-MIT

**Comment by danheberden** [comment]
Do you think it would be better to simply point this at a public resource like `https://github.com/jquery/jquery/blob/master/MIT-LICENSE.txt` or ask the user for their url/issues-url similar to grunt-init?

**Comment by necolas** [comment]
I wouldn't like to another project. Maybe best to not include it at all.

**Comment by paulirish** [comment]
Solution: https://github.com/remy/mit-license

**Comment by danheberden** [comment]
Fixed with https://github.com/danheberden/yeoman-generator-requirejs/commit/671cf8b7d4ce613be5e0f31e61d2b30c9926ddc6 specifically
