### ISSUE TITLE
Fix outdated dependencies

### ISSUE THREAD

**Issue by fhemberger** [danheberden/yeoman-generator-requirejs#6]
Maybe you should change the required version of the grunt plugins to "*", e.g. grunt-contrib-jshint is already at v0.5.4 now, but still ~0.1.1 is required in your package.json.

This would make it much easier to keep the generator up to date (and I guess the grunt API won't undergo breaking changes in the 0.4 branch).

**Comment by danheberden** [comment]
Good point, but wouldn't be great to get that left in by accident; perhaps the deps should be moved as commands to install via bower. I.e., just install all the deps with `npm install dev --save-dev` to get the latest version at the time.

**Comment by fhemberger** [comment]
I don't know if I understood you right, but using "*" as a version "number" for dependencies in your package.json/bower.json will always install the latest version automatically. So that would be a good idea in general. No need for a separate command to run.

**Comment by danheberden** [comment]
Yes, you're definitely right about that. My only concern is that `package.json` file that would be added (and used) in the project would have `*` listed as the dep version; I know it's the burden/problem/whatever of the consumer to change this, but I'd rather it not be the default. 

My thinking was to manually `npm install whatever --save-dev` which would add `~x.x.x`'s latest version into the resulting scaffolded project's `package.json`. It seems better that this functionality would just read the `package.json` file, fetch the latest versions with --save-dev, which would update the `package.json` file automatically.

**Comment by fhemberger** [comment]
Whatever floats your boat. ;)

**Comment by danheberden** [comment]
Heh; in the mean time, we should follow your advice re: `*`

**Comment by danheberden** [comment]
https://github.com/danheberden/yeoman-generator-requirejs/commit/5abf074f60d2d837ac6fff3ab275f45280bdce09
